apiVersion: triliovault.trilio.io/v1
kind: License
metadata:
    name: trilio-license
spec:
    key: xLENDgwKD3jafZFRb4IwFIXf+yua7LlJW2GICQ8O60JkaAR8XUq9Zk20kAJm/vuBmsyA8Tz2nny359y3rAW8AIWxj5k3c9nMYZhT7qLQgmx0aRayAfyvoB8Sxgn1kdjr3oEHCpYWILNaHpFUjT4DHjka2wI6agWmhh3Y+pEScPQltWnASKNA/FbaXm6f6He/E8r63WF5qqS5jMjZNoqjNVnlH2KbiEykJI5CkaSCfIqELLdCfHeWeYyS9lSAXR/yutv/ACAMpWDPYKPFkJ2UBlAqEvxEQfdOCq8oHOCK7F3uEcYOlExdLonDKXXA8Z0JpSi+xR7ig2w3z+PsziimLxnXVuSo/MeCNq1VP7KGF/dLVVnBkyjXnKu2gHzUwX0Yykoq3QzrDxjthMNNXv8BN/mPvjAtAhQcXQobZJTvTzNVd187lnyP2m17DwIVAKgZr+kYAUHIqNRTjlRHv18EOm1PX02f7